name: Deploy AWS Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy AWS Infrastructure
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy S3 Bucket
        run: |
          aws s3api create-bucket --bucket shirinresume --region $AWS_REGION --create-bucket-configuration LocationConstraint=$AWS_REGION || echo "Bucket may already exist."

      - name: Describe ACM Certificate
        run: |
          aws acm describe-certificate --certificate-arn arn:aws:acm:us-east-1:610229897684:certificate/81dcfc27-c159-4fd0-a7cb-2b5e47fde4bc || echo "ACM Certificate not found."

      - name: Describe DynamoDB Table
        run: |
          aws dynamodb describe-table --table-name shirintechvisitorcounter || echo "DynamoDB table not found."

      - name: Check Lambda Function
        run: |
          aws lambda get-function --function-name shirinvisitorcount || echo "Lambda function not found."

      - name: Check Route 53 Hosted Zones
        run: |
          aws route53 list-hosted-zones || echo "No hosted zones found."
